version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 5s
  
  app:
    build: .
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_CONNECTION_STRING: postgresql://postgres:example@db:5432/db